In [83]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
import csv
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.layers import *
from tensorflow.keras.applications import *
from tensorflow.keras.models import Model 
from tensorflow.keras.models import *
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

import random

In [84]:

df = pd.read_csv('/content/categories_4.csv', low_memory=False)
#df.loc[df['CustomerId']==340]
df.tail()

                0        1  2  3  4             5
888     سندوتشات   الباستا  0  0  0     سندوتشات
889         الفتة  الباستا  0  0  0         الفتة
890         الفتة        0  0  0  0         الفتة
891  اطباق رئيسية        0  0  0  0  اطباق رئيسية
892       الباستا        0  0  0  0       الباستا

In [85]:
print(df.columns)

Index(['0', '1', '2', '3', '4', '5'], dtype='object')

In [86]:
classes = len(df['5'].unique())

In [87]:
df['5'].unique()

array(['بيتزا ايطالى', 'اطباق المشويات', 'اطباق رئيسية', 'الباستا',
       'المشروبات الساخنة', 'المشروبات الباردة', 'طواجن', 'الفتة',
       'منيو رمضان', 'مشويات رمضان', 'سندوتشات ', 'مشويات بالكيلو',
       'العصائر', 'السلاطات', 'الارز', 'الشوربة', 'Dessert',
       'سي فوود رمضان', 'الكوكتيلات'], dtype=object)

In [88]:
x= [len(df.loc[df['5']==i])  for i in df['5'].unique()]
x

[198, 65, 120, 188, 14, 2, 13, 22, 69, 19, 65, 80, 1, 14, 2, 11, 8, 1, 1]

In [89]:
#columns = [(i,j) for i,j in enumerate(df.columns)]
#columns

In [90]:
labels = df['5']
del df['5']
df.head()

                0  1  2  3  4
0    بيتزا ايطالى  0  0  0  0
1    بيتزا ايطالى  0  0  0  0
2  اطباق المشويات  0  0  0  0
3    بيتزا ايطالى  0  0  0  0
4    اطباق رئيسية  0  0  0  0

In [91]:
df = pd.get_dummies(df)

df.head()

   0_Dessert  0_اطباق المشويات  ...  4_مشويات رمضان  4_منيو رمضان
0          0                 0  ...               0             0
1          0                 0  ...               0             0
2          0                 1  ...               0             0
3          0                 0  ...               0             0
4          0                 0  ...               0             0

[5 rows x 88 columns]

In [92]:
labels = pd.get_dummies(labels)
labels = labels.values

In [93]:
data = np.array(df)
labels = np.array(labels)

In [94]:
data=data.reshape(-1,88,1)
print(data.shape)

(893, 88, 1)

In [95]:
data = data.astype('float32') 
print(data.dtype)

float32

In [96]:
def Model():
    
    tf.keras.backend.clear_session()
    tf.random.set_seed(51)
    np.random.seed(51)


    model= tf.keras.models.Sequential([


       tf.keras.layers.LSTM(16,input_shape=(data.shape[1],1), return_sequences=True),

        tf.keras.layers.LSTM(16),
                 tf.keras.layers.Flatten(),

         tf.keras.layers.Dense(64, activation='relu'),
          tf.keras.layers.Dense(32, activation='relu'),
         tf.keras.layers.Dense(classes, activation='softmax'),

    ])

    model.compile(loss='categorical_crossentropy',  optimizer='adam',metrics = 'accuracy')
    
    return model

In [97]:
checkpoint_filepath = 'best_model'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_loss',
    mode='min',
    verbose=1,
    save_best_only=True)

In [98]:
model= Model()
history = model.fit(data,labels,epochs=3,verbose=1,callbacks=[model_checkpoint_callback],validation_split=0.2,batch_size=32,shuffle=True)

Epoch 1/3
23/23 [==============================] - 5s 76ms/step - loss: 2.9307 - accuracy: 0.1293 - val_loss: 2.8542 - val_accuracy: 0.1508

Epoch 00001: val_loss improved from inf to 2.85422, saving model to best_model
Epoch 2/3
23/23 [==============================] - 1s 38ms/step - loss: 2.7275 - accuracy: 0.1371 - val_loss: 2.4741 - val_accuracy: 0.1508

Epoch 00002: val_loss improved from 2.85422 to 2.47414, saving model to best_model
Epoch 3/3
23/23 [==============================] - 1s 38ms/step - loss: 2.3537 - accuracy: 0.2194 - val_loss: 2.3461 - val_accuracy: 0.1508

Epoch 00003: val_loss improved from 2.47414 to 2.34608, saving model to best_model